### ISSUE TITLE
issue-1-see-car

### ISSUE THREAD

**Issue by david-s-song** [david-s-song/driving-game#1]

**Comment by david-s-song** [comment]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Make background color green
- [x] Create racing car 
- [x] Fix all errors
