### ISSUE TITLE
issue-2-turn-car

### ISSUE THREAD

**Issue by david-s-song** [david-s-song/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Query the racing car.
- [x] Query the body element.
- [x] Create a function to respond to arrow keys using e.keyCode.
- [x] Create a function to rotate the car using the transform property.
- [x] Create an event listener for the HTML body element on 'key down' event.
